# Generated by Django 4.1.1 on 2022-10-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatim1', '0002_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='retete',
            old_name='data',
            new_name='date',
        ),
    ]
